import { ObjectId } from "mongodb";
import mongoose from "mongoose";

export const recipeCollection = "recipes";

export const recipeSchema = {
  userId: ObjectId,
  name: String,
  prepTime: Number,
  cookTime: Number,
  totalTime: Number,
  servings: Number,
  ingredients: [String],
  instructions: [String],
  imageUrl: { type: String, required: false },
  cuisineRegion: {
    type: String,
    enum: [
      "Latin American",
      "Caribbean",
      "North American",
      "Middle Eastern",
      "East Asian",
      "Southeast Asian",
      "South Asian",
      "European",
      "African",
      "Hawaiian/Pacific Islands",
      "Other",
    ],
    required: true,
  },
  proteinChoice: {
    type: String,
    enum: [
      "Plant-based",
      "Egg",
      "Chicken",
      "Fish",
      "Shellfish",
      "Beef",
      "Pork",
      "Lamb",
      "Other animal based",
      "None",
    ],
    required: true,
  },
  dietaryRestriction: {
    type: String,
    enum: [
      "Vegan",
      "Vegetarian",
      "Pescatarian",
      "Nut-free",
      "Gluten-free",
      "Dairy-free",
      "Shellfish-free",
      "Paleo",
      "Keto",
      "Low-carb",
    ],
    required: false,
  },
  religiousRestriction: {
    type: String,
    enum: ["Halal", "Kosher", "Kosher Parve", "Hindu"],
    required: false,
    default: "None",
  },
  totalLikes: { type: Number, default: 0 },
  totalReviews: { type: Number, default: 0 },
  averageReviewRating: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
};
