import { ObjectId } from "mongodb";

export const recipeCollection = "recipes";

export const recipeSchema = {
  userId: ObjectId,
  name: String,
  description: {
    type: String,
    required: true,
    maxlength: 300,
  },
  prepTime: Number,
  cookTime: Number,
  totalTime: Number,
  servings: Number,
  ingredients: [String],
  instructions: [String],
  imageUrls: {
    type: [String],
    required: true,
    validator: (arr) => arr.length >= 0 && arr.length <= 3,
    message:
      "You must provide at least 1 imageUrl or a maximum of 3 image URLs.",
  },
  cuisineRegion: {
    type: String,
    enum: [
      "Latin American",
      "Caribbean",
      "North American",
      "Middle Eastern",
      "East Asian",
      "Southeast Asian",
      "South Asian",
      "European",
      "African",
      "Hawaiian/Pacific Islands",
      "Other",
    ],
    required: true,
  },
  cuisineSubregion: { type: String, required: false },
  proteinChoice: {
    type: String,
    enum: [
      "Plant-based",
      "Egg",
      "Chicken",
      "Fish",
      "Shellfish",
      "Beef",
      "Pork",
      "Lamb",
      "Other animal based",
      "None",
    ],
    required: true,
  },
  dietaryRestriction: {
    type: String,
    enum: [
      "Vegan",
      "Vegetarian",
      "Pescatarian",
      "Nut-free",
      "Gluten-free",
      "Dairy-free",
      "Shellfish-free",
      "Paleo",
      "Keto",
      "Low-carb",
    ],
    required: false,
  },
  religiousRestriction: {
    type: String,
    enum: ["Halal", "Kosher", "Kosher Parve", "Hindu"],
    required: false,
    default: "None",
  },
  authorNotes: { type: [String], required: false },
  equipment: { type: [String], required: false },
  createdAt: { type: Date, default: Date.now },
};
